services:
  whisper:
    image: aisflow/whisper
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']
    ports:
      - '8484:8484'
    stdin_open: true
    tty: true
