# .github/workflows/tag-on-version.yml
name: Create Tag on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: package-version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.package-version.outputs.version }}

          TAG_NAME="v$VERSION"

          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping."
          else
            echo "Creating and pushing tag $TAG_NAME"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi
